import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

// Ported verbatim from the approved "Lakeside Heritage" (Stitch/Neo) design.
// Fonts are wired to next/font CSS variables set in app/layout.tsx.
const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#d3c4b8",
        "surface-variant": "#e4e2dd",
        secondary: "#685c53",
        "on-surface-variant": "#44474e",
        primary: "#002046",
        background: "#fbf9f4",
        "outline-variant": "#c4c6cf",
        "surface-container-highest": "#e4e2dd",
        "sunset-accent": "#E69A8D",
        outline: "#74777f",
        "on-secondary": "#ffffff",
        charcoal: "#2D2D2D",
        "primary-fixed": "#d6e3ff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#221a13",
        "tertiary-fixed": "#d3e8d5",
        "surface-bright": "#fbf9f4",
        "surface-dim": "#dbdad5",
        "on-primary-container": "#87a0cd",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#0e1f13",
        tertiary: "#132418",
        "on-tertiary-container": "#8fa492",
        "surface-container-high": "#eae8e3",
        "tertiary-container": "#283a2d",
        surface: "#fbf9f4",
        "on-error": "#ffffff",
        "inverse-primary": "#aec7f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-white": "#FFFFFF",
        "tertiary-fixed-dim": "#b7ccb9",
        "inverse-surface": "#30312e",
        "secondary-fixed": "#f0e0d3",
        "on-tertiary-fixed-variant": "#394b3d",
        "secondary-container": "#f0e0d3",
        "primary-container": "#1b365d",
        "on-primary-fixed-variant": "#2e476f",
        "on-primary-fixed": "#001b3d",
        "on-secondary-fixed-variant": "#4f453c",
        "on-secondary-container": "#6e6258",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#aec7f7",
        "on-primary": "#ffffff",
        "on-surface": "#1b1c19",
        "surface-tint": "#465f88",
        "inverse-on-surface": "#f2f1ec",
        "surface-container": "#f0eee9",
        "on-background": "#1b1c19",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        "section-gap": "80px",
        gutter: "24px",
        "container-max-width": "1280px",
        "margin-mobile": "16px",
        unit: "8px",
      },
      maxWidth: {
        "container-max-width": "1280px",
      },
      fontFamily: {
        "headline-md": ["var(--font-playfair)", "serif"],
        "label-lg": ["var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-playfair)", "serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "display-lg-mobile": ["var(--font-playfair)", "serif"],
        "headline-lg": ["var(--font-playfair)", "serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        script: ["var(--font-great-vibes)", "cursive"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "display-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [forms],
};

export default config;
